server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:1101/jobConnect
    username: admin
    password: admin@123


  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: sprngtesting@gmail.com
    password: expc hqrr txzt sgel
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    redis:
      port: 6379
      host: localhost
      password: Admin@123
      username: admin
  cache:
    type: redis