server:
  port: ${SERVER_PORT:8080}

spring:

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://db.eloiigagrzawkzuprroc.supabase.co:5432/postgres}
    username: ${DATABASE_USER_NAME:postgres}
    password: ${DATABASE_PASSWORD:Postgres@1232}

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: ${MAIL_HOST:live.smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:smtp@mailtrap.io}
    password: ${MAIL_PASSWORD:8baadd316f92df073609205269251e75}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:your-access-key-id}
      secret-key: ${AWS_SECRET_ACCESS_KEY:your-secret-access-key}
    region: ${AWS_REGION:ap-south-1}
    stack:
      auto: false
app:
  s3:
    bucket: ${AWS_S3_BUCKET:jobresumes3}