server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:1101/jobConnect
    username: admin
    password: admin@123


  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update